##### We are goint to Analyse the Netflix userbase Data and will deepdive on some Stats concepts 
#### Link of the dataset - https://www.kaggle.com/datasets/riturajsingh99/netflix-userbase/discussion?sort=hotness

##### We have taken the data set from kaggle

In [2]:
import numpy as np 
import pandas as pd

In [4]:
df=pd.read_csv("netflix.csv")
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,15-01-22,10-06-23,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,05-09-21,22-06-23,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,28-02-23,27-06-23,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,10-07-22,26-06-23,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,01-05-23,28-06-23,Germany,33,Male,Smartphone,1 Month

In [5]:
df.shape

(2500, 10)

In [7]:
df.describe()

          User ID  Monthly Revenue          Age
count  2500.00000      2500.000000  2500.000000
mean   1250.50000        12.508400    38.795600
std     721.83216         1.686851     7.171778
min       1.00000        10.000000    26.000000
25%     625.75000        11.000000    32.000000
50%    1250.50000        12.000000    39.000000
75%    1875.25000        14.000000    45.000000
max    2500.00000        15.000000    51.000000

In [12]:
df["Monthly Revenue"].count()
mean_val=df["Monthly Revenue"].mean()
mean_val
# from this mean value we can say the on an avg 12.5$ is paid by per user to netflix each month

np.float64(12.5084)

In [20]:
median_val=df["Monthly Revenue"].median()
median_val
mode_val=df["Monthly Revenue"].mode()

mode_val

0    12
Name: Monthly Revenue, dtype: int64

In [ ]:
range_of_revnue=df["Monthly Revenue"].max()-df["Monthly Revenue"].min()
range_of_revnue

np.int64(5)

In [ ]:
variance_of_rev=df["Monthly Revenue"].var()
variance_of_rev

np.float64(2.84546762705082)

In [25]:
std_dev_of_rev=df["Monthly Revenue"].std()
std_dev_of_rev

np.float64(1.6868513944775396)

In [ ]:
Q1=df["Monthly Revenue"].quantile(0.25)
Q2=df["Monthly Revenue"].quantile(0.50)
Q3=df["Monthly Revenue"].quantile(0.75)



print("25% Users pay ",Q1,"$ permonth")
print("50% Users pay ",Q2,"$ permonth")
print("75% Users pay ",Q3,"$ permonth")

11.0  -  12.0  -  14.0
25% Users pay  11.0 $ permonth
50% Users pay  12.0 $ permonth
75% Users pay  14.0 $ permonth

In [ ]:
#InterQuartile Range  - It tell us the Spread of middle 50% of the data 

# Interquartile range = Q3-Q1

IQR=df["Monthly Revenue"].quantile(0.75)-df["Monthly Revenue"].quantile(0.25)
IQR
# The middle of the 50% user have revenues spread accross $3 range

np.float64(3.0)

In [ ]:
# Skew 
skew=df["Monthly Revenue"].skew()
skew

# Skew=0 - Perefectly symmetric - bell curve 
# skew >0 positive : Long tail on right side 
# skew <0 negative : Long tail on left side

np.float64(-0.01626526879982235)

In [35]:
frqncy_of_revenue=df["Monthly Revenue"].value_counts()
frqncy_of_revenue

Monthly Revenue
12    455
14    431
13    418
10    409
15    399
11    388
Name: count, dtype: int64

In [43]:
tot_user=df["Monthly Revenue"].count()
prem_user=df[df["Monthly Revenue"]==15]["Monthly Revenue"].count()
prob=prem_user/tot_user
print(prob*100," % Chances that the user will be premium ")

15.959999999999999  % Chances that the user will be premium

In [46]:
df.groupby("Subscription Type")["Monthly Revenue"].mean().sort_values()

Subscription Type
Standard    12.464844
Basic       12.481481
Premium     12.590723
Name: Monthly Revenue, dtype: float64

In [51]:
df.groupby("Subscription Type")["Monthly Revenue"].agg(["count","mean","std","median"])

                   count       mean       std  median
Subscription Type
Basic                999  12.481481  1.681983    12.0
Premium              733  12.590723  1.733319    13.0
Standard             768  12.464844  1.647190    12.0

### Task Calculate all the values manually without using inbuilt functions 
1 mean ,median ,mode
2 stdDeviation & variance 
and use groupby and agg functions on the given dataset and Do proper EDA