### Statistic 
#### Completed Topics --  Mean Median Mode
##### Variance , Standard Deviation , Percentiles ,Quartiles  ,Skewness , Outlier detection

In [62]:
import numpy as np 

sales_data =[12,15,18,22,25,28,30,35,40,45,50,55,60,65,70,75,80,85,90,95,100,102,105
,109,110,115,120,125,130,135,140,145,150,155,160,165,170,175,180,185,190,195,200]


mean_sales=np.mean(sales_data)

print(mean_sales)

deviation=[x-mean_sales for x in sales_data] # Here we are using list comprehension

101.30232558139535

In [63]:
variance=[(x-mean_sales)**2 for x in sales_data]
print(sum(variance)/len(sales_data))

finalVariance=np.var(sales_data)
print(finalVariance )

3156.3504597079495
3156.3504597079504

In [64]:
mark=[12,15,22,13,20,25,30]

meanData=np.mean(mark)
print(meanData)

varian=[(i-meanData)**2 for i in mark]
print(sum(varian)/len(mark))

print(np.var(mark))

19.571428571428573
37.95918367346939
37.95918367346939

In [65]:
demo=[10,20,30]
print(np.mean(demo))
deviation=[(x-np.mean(demo))**2 for x in demo]

20.0

In [66]:
std_dev=np.sqrt(np.var(demo))
print(std_dev)
np.std(demo)

8.16496580927726

np.float64(8.16496580927726)

In [73]:
import pandas as pd
import numpy as np 

df=pd.read_csv("netflix.csv")
df.head()

,User ID,Subscription Type,Monthly Revenue,Join Date,Last Payment Date,Country,Age,Gender,Device,Plan Duration
0,1,Basic,10,15-01-22,10-06-23,United States,28,Male,Smartphone,1 Month
1,2,Premium,15,05-09-21,22-06-23,Canada,35,Female,Tablet,1 Month
2,3,Standard,12,28-02-23,27-06-23,United Kingdom,42,Male,Smart TV,1 Month
3,4,Standard,12,10-07-22,26-06-23,Australia,51,Female,Laptop,1 Month
4,5,Basic,10,01-05-23,28-06-23,Germany,33,Male,Smartphone,1 Month

In [68]:
df.describe()

          User ID  Monthly Revenue          Age
count  2500.00000      2500.000000  2500.000000
mean   1250.50000        12.508400    38.795600
std     721.83216         1.686851     7.171778
min       1.00000        10.000000    26.000000
25%     625.75000        11.000000    32.000000
50%    1250.50000        12.000000    39.000000
75%    1875.25000        14.000000    45.000000
max    2500.00000        15.000000    51.000000

In [74]:
print("Total Users are ",len(df))
print("Total number of Cols ",len(list(df.columns)))
print("Col Names:",list(df.columns))

Total Users are  2500
Total number of Cols  10
Col Names: ['User ID', 'Subscription Type', 'Monthly Revenue', 'Join Date', 'Last Payment Date', 'Country', 'Age', 'Gender', 'Device', 'Plan Duration']

In [85]:
revenue=df["Monthly Revenue"]
# print(revenue.nlargest(10))
# print(revenue.nsmallest(10))
variance=revenue.var()
print(variance)


if variance<10 :
    print("The data is less variance mean all the user are giving almost same revenue")
elif variance <50:
    print("The data is moderate variance mean all the user are giving almost same revenue")
else:
    print("The data is high variance mean all the user are giving different revenue")

2.84546762705082
The data is less variance mean all the user are giving almost same revenue

  Stats  is of Two Types :
        Descriptive Stats  - Past data insights 
        Inferentials stat - for future predictions 

Class A  - 70 70 70 70 70   Average - 70 
Class B  - 20 40 70 100 120 Average - 70  
Variance - How far the data points are spread out from the mean value

In [96]:
data=[2,4,6,8]
mean_val=np.mean(data)
print(mean_val)

# 2-5= -3**2 -> 9
# 4-5= -1**2 -> 1
# 6-5= 1**2 -> 1
# 8-5= 3**2 -> 9
variance=[(x-mean_val)**2 for x in data]
print(sum(variance)/len(data))
np.var(data)

5.0
5.0

np.float64(5.0)

In [102]:
import pandas as pd 
scores=[45,50,52,55,58,62,65,60,65,70,75,72,77,82,80,85,90,95,100,150]

print(np.var(scores),"Variance ")

print(np.std(scores),"Standard Deviation ")

print(np.mean(scores),"Mean ")

print(pd.Series(scores).std(),"This is how you will calculate Standard Deviations in pandas ")

520.8399999999999 Variance
22.8219192882632 Standard Deviation
74.4 Mean
23.414795142792673 This is how you will calculate Standard Deviations in pandas

### Percentile - what percentage of observations  lie a below value 

##### Lets suppose you got  95 percentile 
##### so you have scored better than 95% students

In [107]:
np.percentile(scores,90)

np.float64(95.5)

#### Quartiles 

______Q1 ______Q2 ______ Q3______

Q1 - 25th percentile  25%
Q2 - 50th percentile  meadian 50%
Q3 - 75th percentile  75%

In [108]:
np.percentile(scores,[25,50,75])

array([59.5 , 71.  , 82.75])

### Task 
1 - Apply all EDA 
2 - Get the complete insights of the data 
3 - Change the col names  with custom names 
$ - find the mean median and mode 
6 - prepare the data summar table for the given data set