In [2]:
import plotly.express as px 
import pandas as pd

In [3]:
df=pd.DataFrame({
    "values":[-10,2,4,5,6,7,8,9,10,30]
})
df

   values
0     -10
1       2
2       4
3       5
4       6
5       7
6       8
7       9
8      10
9      30

In [6]:
fig=px.box(df,x="values",points="outliers",title="My Data ")
fig.update_layout(width=800,height=400)
fig.show()

In [9]:
comp_A=[480,500,510,520,530,540,
        550,570,580,590,600,560,
        610,620,630,640,650,660
        ]
comp_B=[300,320,340,370,390,400,
        380,400,390,430,440,500,
        480,540,600,850,1200,1220]

comp_C=[50,100,250,700,750,800,
        740,750,760,780,790,810,
        800,810,820,830,840,900]

df=pd.DataFrame({
    "A":comp_A,
    "B":comp_B,
    "C":comp_C
})

df

      A     B    C
0   480   300   50
1   500   320  100
2   510   340  250
3   520   370  700
4   530   390  750
5   540   400  800
6   550   380  740
7   570   400  750
8   580   390  760
9   590   430  780
10  600   440  790
11  560   500  810
12  610   480  800
13  620   540  810
14  630   600  820
15  640   850  830
16  650  1200  840
17  660  1220  900

### Sampling

In [10]:
import numpy as np 
import pandas as pd

In [ ]:
np.random.seed(42)

df=pd.DataFrame({ "ID":range(1,1001),"Gender":np.random.choice(["Male","Female"],size=1000,p=[0.7,0.3]
    ),
    "Marks":np.random.randint(40,100,1000)
})
df.head()

   ID  Gender  Marks
0   1    Male     86
1   2  Female     51
2   3  Female     55
3   4    Male     63
4   5    Male     58

### Simple Random Sampling (SRS)
in this sampling every students have equal chance to be selected because we are selecting randomly

In [24]:
srs=df.sample(n=100,random_state=42)

srs.shape

(100, 3)

In [25]:
print(df["Marks"].mean()) ### Origin large data 
print(srs["Marks"].mean()) ### sample data taken from the original data

69.508
70.89

### Startified Sampling method 
Making the groups before taking the sample data 
 then after creating the groups then  slecting the sample data from the groups and combine them to use  

 ##### These groups are called Strata

In [29]:
print(df["Gender"].value_counts())

Gender
Male      712
Female    288
Name: count, dtype: int64

In [41]:
male_data=df[df["Gender"]=="Male"].sample(n=50,random_state=45)
fem_data=df[df["Gender"]=="Female"].sample(n=50,random_state=45)

# Here we have created Two startas male_data and fem_data

# Now we are going to add both the data together to get the final sample data 

final_data=pd.concat([male_data,fem_data])

final_data.shape

(100, 3)